import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const html=readFileSync(new URL('../web/index.html',import.meta.url),'utf8');
const css=readFileSync(new URL('../web/style.css',import.meta.url),'utf8');
const manifest=JSON.parse(readFileSync(new URL('../web/site.webmanifest',import.meta.url),'utf8'));
const worker=readFileSync(new URL('./index.ts',import.meta.url),'utf8');
const app=readFileSync(new URL('../web/app.js',import.meta.url),'utf8');
const config=readFileSync(new URL('../wrangler.jsonc',import.meta.url),'utf8');
const migration=readFileSync(new URL('../migrations/0003_main_entrance_default.sql',import.meta.url),'utf8');
const serviceWorker=readFileSync(new URL('../web/sw.js',import.meta.url),'utf8');
const png=(name)=>{const data=readFileSync(new URL(`../web/${name}`,import.meta.url));return {width:data.readUInt32BE(16),height:data.readUInt32BE(20),colorType:data[25]}};

test('manifest launches the minimal app in standalone mode',()=>{assert.equal(manifest.display,'standalone');assert.equal(manifest.start_url,'/');assert.equal(manifest.scope,'/');assert.equal(manifest.theme_color,manifest.background_color);assert.deepEqual(manifest.icons.map(icon=>icon.sizes),['192x192','512x512','192x192','512x512']);assert.deepEqual(manifest.icons.map(icon=>icon.purpose),['any','any','maskable','maskable'])});
test('iPhone Home Screen metadata and all safe areas are present',()=>{for(const value of ['apple-mobile-web-app-capable','apple-mobile-web-app-title','apple-mobile-web-app-status-bar-style','viewport-fit=cover','apple-touch-icon'])assert.match(html,new RegExp(value));for(const value of ['safe-area-inset-top','safe-area-inset-bottom','safe-area-inset-left','safe-area-inset-right','100dvh','overflow-x:hidden','touch-action:manipulation'])assert.ok(css.includes(value))});
test('favicon, Apple icon, and manifest icons are referenced',()=>{assert.match(html,/rel="icon" href="\/icon\.svg"/);assert.match(html,/rel="apple-touch-icon" sizes="180x180" href="\/apple-touch-icon\.png"/);for(const icon of manifest.icons)assert.match(serviceWorker,new RegExp(icon.src.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('app icons have exact opaque dimensions',()=>{for(const [name,size] of [['apple-touch-icon.png',180],['icon-192.png',192],['icon-512.png',512],['icon-maskable-192.png',192],['icon-maskable-512.png',512]]){const image=png(name);assert.deepEqual([image.width,image.height],[size,size]);assert.equal(image.colorType,2)}});
test('service worker is registered and uses the refreshed shell cache',()=>{assert.match(app,/navigator\.serviceWorker\.register\('\/sw\.js'\)/);assert.match(serviceWorker,/brp-open-v5/)});
test('minimal navigation contains Open and Create tabs',()=>{assert.match(app,/data-tab="open"/);assert.match(app,/data-tab="create"/);assert.match(app,/class="tab/);assert.match(app,/aria-current="page"/);assert.doesNotMatch(app,/Dina readers|Senaste aktivitet|reader-grid|raw ID|workspace/)});
test('login is a one-time form backed by the session cookie, not a per-action modal',()=>{assert.match(app,/id="login-view"/);assert.match(app,/\/api\/login/);assert.doesNotMatch(app,/id="credentials"/);assert.doesNotMatch(app,/\/api\/open-door/);assert.doesNotMatch(app,/localStorage|sessionStorage|indexedDB/)});
test('Create tab supports both a server preset and a validated custom major/minor beacon',()=>{assert.match(app,/id="create-view"/);assert.match(app,/name="name" value="Main entrance"/);assert.match(app,/name="major" inputmode="numeric" pattern="\[0-9\]\{1,12\}"/);assert.match(app,/name="minor" inputmode="numeric" pattern="\[0-9\]\{1,12\}"/);assert.match(app,/reportValidity/);assert.match(app,/\/api\/readers/)});
test('session-based reader and passage routes are wired',()=>{assert.match(worker,/path==='\/api\/readers'/);assert.match(worker,/requireSession/);assert.match(worker,/lookupPassageReader/)});
test('open request authenticates via session cookie and CSRF, never resending the password',()=>{const openBlock=app.slice(app.indexOf("form.id==='open-view'"),app.indexOf("form.id==='create-view'"));assert.match(openBlock,/\/api\/readers\/\$\{selectedReader\}\/passage/);assert.match(openBlock,/x-csrf-token/);assert.doesNotMatch(openBlock,/password/);assert.doesNotMatch(config,/PASSAGE_CARD_READER/)});
test('major and minor are encrypted and reader lookup is owner scoped',()=>{assert.match(worker,/encryptJson\(\{major:result\.major,minor:result\.minor\}/);assert.match(worker,/WHERE id=\? AND owner_id=\? AND config_ciphertext IS NOT NULL/);assert.match(worker,/decryptJson/)});
test('configured creation can upgrade a hidden legacy reader',()=>{assert.match(worker,/saveConfiguredReader/);assert.match(worker,/id:savedId,name:result\.name/)});
test('production opening remains disabled in committed configuration',()=>{assert.match(config,/"PASSAGE_ENABLED": "false"/)});
test('default reader is Main entrance and migration leaves encrypted readers untouched',()=>{assert.match(worker,/'Main entrance','main entrance'/);assert.match(migration,/name = 'Main entrance'/);assert.match(migration,/config_ciphertext IS NULL/);assert.match(migration,/NOT EXISTS/)});
test('iPhone 13 controls are touch friendly and cannot overflow',()=>{assert.match(css,/min-height:48px/);assert.match(css,/max-width:390px/);assert.match(css,/@media\(max-width:430px\)/);assert.match(css,/\*\{box-sizing:border-box;min-width:0\}/);assert.match(css,/\.app-shell\{[^}]*width:100%;[^}]*min-height:100dvh/)});
test('bottom navigation respects the Home indicator',()=>{assert.match(css,/\.tab-bar/);assert.match(css,/safe-bottom/);assert.match(css,/grid-template-columns:1fr 1fr/)});
